{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GcCardReader","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"GcCardReader","externalID":"c:@M@GCCardReader@objc(cs)GcCardReader","modules":[{"name":"GCCardReader"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GcCardReader"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0","name":"iOS"}],"navigatorTitle":[{"text":"GcCardReader","kind":"identifier"}],"roleHeading":"Class","role":"symbol","symbolKind":"class"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"GcCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection."}],"variants":[{"paths":["\/documentation\/gccardreader\/gccardreader"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/gccardreader\/gccardreader"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/didNFCConnectionFailed","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/logsFromGCCardReader","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/nfcConnectionLostMessage","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/showNFCDisplayMessage"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/connectNFCCard(dateOfBirth:expiryDate:cardNumber:tags:successCallback:)","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/nProbe(nfcScanResult:ocrScanResult:passportNumber:numberOfDependents:successCallback:failureCallback:)","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/scanEIDACard(on:successCallback:failureCallback:)","doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/scanEIDACardFront(on:successCallback:failureCallback:)"]},{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/shared"],"title":"Type Properties"},{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/initialise(callBack:)"],"title":"Type Methods"},{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/NfcReaderDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSURLSessionDelegate","doc:\/\/com.gamechange.GCCardReader\/9NFCReader17NfcReaderDelegateP","doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSObject","doc:\/\/com.gamechange.GCCardReader\/s7CVarArgP","doc:\/\/com.gamechange.GCCardReader\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCCardReader\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCCardReader\/SQ","doc:\/\/com.gamechange.GCCardReader\/SH","doc:\/\/com.gamechange.GCCardReader\/objc(pl)WKNavigationDelegate"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/connectNFCCard(dateOfBirth:expiryDate:cardNumber:tags:successCallback:)":{"url":"\/documentation\/gccardreader\/gccardreader\/connectnfccard(dateofbirth:expirydate:cardnumber:tags:successcallback:)","kind":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/connectNFCCard(dateOfBirth:expiryDate:cardNumber:tags:successCallback:)","type":"topic","abstract":[{"type":"text","text":"Connect NFC Card to read the chip data. Returns callback on background thread."}],"title":"connectNFCCard(dateOfBirth:expiryDate:cardNumber:tags:successCallback:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"connectNFCCard","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"expiryDate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"cardNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tags","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"GCDataGroupId","preciseIdentifier":"s:12GCCardReader13GCDataGroupIdO"},{"kind":"text","text":"], "},{"text":"successCallback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12GCCardReader12EIDACardDataV","kind":"typeIdentifier","text":"EIDACardData"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}]},"doc://com.gamechange.GCCardReader/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCCardReader\/SQ"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/scanEIDACardFront(on:successCallback:failureCallback:)":{"url":"\/documentation\/gccardreader\/gccardreader\/scaneidacardfront(on:successcallback:failurecallback:)","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/scanEIDACardFront(on:successCallback:failureCallback:)","type":"topic","abstract":[{"type":"text","text":"Scan front side of EIDA card"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanEIDACardFront","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successCallback"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"cardImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"faceImage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"uncroppedCardImage","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"), ","kind":"text"},{"text":"failureCallback","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"))","kind":"text"}],"title":"scanEIDACardFront(on:successCallback:failureCallback:)"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/scanEIDACard(on:successCallback:failureCallback:)":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/scanEIDACard(on:successCallback:failureCallback:)","kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/scaneidacard(on:successcallback:failurecallback:)","role":"symbol","abstract":[{"type":"text","text":"Scan back side of EIDA card"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanEIDACard","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"successCallback","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EIDAScanResult","preciseIdentifier":"s:12GCCardReader14EIDAScanResultV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"isCropped","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failureCallback"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"title":"scanEIDACard(on:successCallback:failureCallback:)"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/didNFCConnectionFailed":{"abstract":[{"type":"text","text":"Error in connecting NFC."}],"title":"didNFCConnectionFailed","type":"topic","url":"\/documentation\/gccardreader\/gccardreader\/didnfcconnectionfailed","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didNFCConnectionFailed"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"GCNFCConnectFailedError","preciseIdentifier":"s:12GCCardReader23GCNFCConnectFailedErrorO"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/didNFCConnectionFailed","kind":"symbol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/NfcReaderDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/NfcReaderDelegate-Implementations","kind":"article","url":"\/documentation\/gccardreader\/gccardreader\/nfcreaderdelegate-implementations","role":"collectionGroup","abstract":[],"title":"NfcReaderDelegate Implementations"},"doc://com.gamechange.GCCardReader/objc(cs)NSObject":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader":{"kind":"symbol","url":"\/documentation\/gccardreader","abstract":[{"type":"text","text":"GCCardReader is a framework used for the scanning of emirates ID cards using either the NFC capability or perform OCR with the camera and then validate the result using the ICA API."}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader","title":"GCCardReader","role":"collection","type":"topic"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/nProbe(nfcScanResult:ocrScanResult:passportNumber:numberOfDependents:successCallback:failureCallback:)":{"abstract":[{"type":"text","text":"Validate EIDA card"}],"title":"nProbe(nfcScanResult:ocrScanResult:passportNumber:numberOfDependents:successCallback:failureCallback:)","type":"topic","url":"\/documentation\/gccardreader\/gccardreader\/nprobe(nfcscanresult:ocrscanresult:passportnumber:numberofdependents:successcallback:failurecallback:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nProbe"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nfcScanResult"},{"kind":"text","text":": "},{"preciseIdentifier":"s:12GCCardReader12EIDACardDataV","text":"EIDACardData","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ocrScanResult","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EIDAScanResult","kind":"typeIdentifier","preciseIdentifier":"s:12GCCardReader14EIDAScanResultV"},{"kind":"text","text":"?, "},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"numberOfDependents","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"successCallback","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"responseData","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12GCCardReader14EIDAOnlineDataV","kind":"typeIdentifier","text":"EIDAOnlineData"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"responseURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qrCode"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"), ","kind":"text"},{"kind":"externalParam","text":"failureCallback"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/nProbe(nfcScanResult:ocrScanResult:passportNumber:numberOfDependents:successCallback:failureCallback:)","kind":"symbol"},"doc://com.gamechange.GCCardReader/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.gamechange.GCCardReader/objc(pl)NSURLSessionDelegate":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSURLSessionDelegate","title":"NSURLSessionDelegate","type":"unresolvable"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/shared":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/shared","kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/shared","role":"symbol","abstract":[{"text":"Shared instance of GcCardReader, use this to access all member functions.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GcCardReader","preciseIdentifier":"c:@M@GCCardReader@objc(cs)GcCardReader","kind":"typeIdentifier"}],"title":"shared"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/nfcConnectionLostMessage":{"url":"\/documentation\/gccardreader\/gccardreader\/nfcconnectionlostmessage","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/nfcConnectionLostMessage","type":"topic","title":"nfcConnectionLostMessage","abstract":[{"text":"Error message to show when card moved away","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfcConnectionLostMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol"},"doc://com.gamechange.GCCardReader/objc(pl)WKNavigationDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)WKNavigationDelegate","title":"WKNavigationDelegate"},"doc://com.gamechange.GCCardReader/9NFCReader17NfcReaderDelegateP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/9NFCReader17NfcReaderDelegateP","type":"unresolvable","title":"NFCReader.NfcReaderDelegate"},"doc://com.gamechange.GCCardReader/SH":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GcCardReader","kind":"identifier"}],"abstract":[{"type":"text","text":"GcCardReader: Defines public class for the framework. Use the shared instance of this to use methods related to card scanning and NFC connection."}],"role":"symbol","url":"\/documentation\/gccardreader\/gccardreader","type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader","title":"GcCardReader","navigatorTitle":[{"text":"GcCardReader","kind":"identifier"}]},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/showNFCDisplayMessage":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/showNFCDisplayMessage","kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/shownfcdisplaymessage","role":"symbol","abstract":[{"text":"Listen to this method to modify NFC Sheet display message based on performed action.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showNFCDisplayMessage","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:12GCCardReader19GCNFCDisplayMessageO","kind":"typeIdentifier","text":"GCNFCDisplayMessage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"showNFCDisplayMessage"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/initialise(callBack:)":{"type":"topic","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/initialise(callBack:)","kind":"symbol","url":"\/documentation\/gccardreader\/gccardreader\/initialise(callback:)","role":"symbol","abstract":[{"text":"Initialises SDK and returns success or error depending on the validity of the license","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callBack","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"title":"initialise(callBack:)"},"doc://com.gamechange.GCCardReader/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.gamechange.GCCardReader/s7CVarArgP":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.gamechange.GCCardReader/objc(pl)NSObject":{"identifier":"doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.gamechange.GCCardReader/documentation/GCCardReader/GcCardReader/logsFromGCCardReader":{"url":"\/documentation\/gccardreader\/gccardreader\/logsfromgccardreader","type":"topic","role":"symbol","identifier":"doc:\/\/com.gamechange.GCCardReader\/documentation\/GCCardReader\/GcCardReader\/logsFromGCCardReader","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logsFromGCCardReader"},{"kind":"text","text":": (("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ())","kind":"text"}],"title":"logsFromGCCardReader","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GcCardReader"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GcCardReader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GcCardReader","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.gamechange.GCCardReader\/objc(pl)NSURLSessionDelegate","doc:\/\/com.gamechange.GCCardReader\/objc(pl)WKNavigationDelegate"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GcCardReader","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"value":"GcCardReader","path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/title","op":"replace"},{"value":[{"text":"GcCardReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.gamechange.GCCardReader~1documentation~1GCCardReader~1GcCardReader\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}